# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

execute:
  execute_notebooks: "off"   # 頁面內用 Thebe 執行就好

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/wendy062644/2025-summer-intern-project-2
  path_to_book: book
  branch: main

html:
  favicon: ""
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org

sphinx:
  extra_extensions:
    - jupyterlite_sphinx
  config:
    myst_title_to_header: true
    html_theme_options:
      # 先關閉下載鈕，等頁面確認是有效 notebook 再打開
      use_download_button: false